title: Project
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type:  text
    width: 3/4
  year:
    label: Year
    type:  number
    width: 1/4
  text:
    label: Text
    type:  textarea
  tags:
    label: Tags
    type:  tags